"""adding image url column

Revision ID: 1c64f5e43789
Revises: eadc6fe8c2a8
Create Date: 2021-08-04 23:22:44.251603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1c64f5e43789"
down_revision = "eadc6fe8c2a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("image_url", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "image_url")
    # ### end Alembic commands ###
