"""adding date and raiting

Revision ID: 53a0362e1b51
Revises: ba7be330148a
Create Date: 2021-08-05 01:42:57.021397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "53a0362e1b51"
down_revision = "ba7be330148a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("rating", sa.Numeric(), nullable=True))
    op.add_column("reviews", sa.Column("rating", sa.Numeric(), nullable=True))
    op.add_column(
        "reviews", sa.Column("datetime", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "datetime")
    op.drop_column("reviews", "rating")
    op.drop_column("products", "rating")
    # ### end Alembic commands ###
