"""adding review id

Revision ID: a2e0869abf09
Revises: c00b9b38ef89
Create Date: 2021-08-05 07:58:44.493398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a2e0869abf09"
down_revision = "c00b9b38ef89"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reviews", sa.Column("review_id", sa.String(), nullable=True)
    )
    op.create_index(
        op.f("ix_reviews_review_id"), "reviews", ["review_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reviews_review_id"), table_name="reviews")
    op.drop_column("reviews", "review_id")
    # ### end Alembic commands ###
