"""adding link column

Revision ID: ba7be330148a
Revises: 1c64f5e43789
Create Date: 2021-08-04 23:23:37.120423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ba7be330148a"
down_revision = "1c64f5e43789"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("link", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "link")
    # ### end Alembic commands ###
