"""adding keywords field

Revision ID: c00b9b38ef89
Revises: 0b43b9043b64
Create Date: 2021-08-05 07:17:16.566069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c00b9b38ef89"
down_revision = "0b43b9043b64"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reviews", sa.Column("keywords", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "keywords")
    # ### end Alembic commands ###
